apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-eks
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.16.2
    helm:
      releaseName: external-secrets
      valueFiles:
        - $values/external-secrets/kkamji_values_eks.yaml
  - repoURL: https://github.com/KKamJi98/helm-charts.git
    targetRevision: main
    ref: values
  destination:
    name: kkamji-al2023
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true