apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    path: metrics-server
    targetRevision: 3.12.2
    helm:
      releaseName: metrics-server
      valueFiles:
      - $values/metrics-server/kkamji_values.yaml
  - repoURL: https://github.com/KKamJi98/helm-charts.git
    targetRevision: main
    ref: values
  destination:
    server: kkamji-al2023
    name: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
