apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.14.3
    helm:
      releaseName: external-secrets
  destination:
    server: 'https://A0A31277A18C3F3DE82CB09570CD6A92.gr7.ap-northeast-2.eks.amazonaws.com'
    namespace: external-secrets
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true