apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-eks
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.0
    helm:
      releaseName: aws-load-balancer-controller
      valueFiles:
        - $values/app-of-apps/applications/aws-lb-controller/values/common.yaml
  - repoURL: https://github.com/KKamJi98/argocd.git
    targetRevision: main
    ref: values
  destination:
    name: kkamji-al2023
    namespace: kube-system
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true