# clusters/prod/root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-bootstrap
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # ① 클러스터 변수 주입
          - list:
              elements:
                - cluster: kkamji-al2023
          # ② Git Directory 스캔 (path만 지정)
          - git:
              repoURL: https://github.com/KKamJi98/argocd.git
              revision: main
              directories:
                - path: app-of-apps/applications/*
  template:
    metadata:
      name: "{{cluster}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/KKamJi98/argocd.git
        path: "{{path}}"
        targetRevision: main
      destination:
        name: kkamji-al2023           # 클러스터 별칭
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
