apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-eks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.14.3
    helm:
      releaseName: external-secrets
      # valueFiles:
      #   - values/common.yaml
  destination:
    name: kkamji-al2023
    namespace: external-secrets
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true