apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: eks
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.14.3
    helm:
      releaseName: external-secrets
      valueFiles:
        - values/common.yaml
  destination:
    name: '{{cluster}}'
    namespace: external-secrets
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true